//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAI.KreationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Log", Namespace="http://schemas.datacontract.org/2004/07/KreationService")]
    [System.SerializableAttribute()]
    public partial class Log : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string branchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string branch {
            get {
                return this.branchField;
            }
            set {
                if ((object.ReferenceEquals(this.branchField, value) != true)) {
                    this.branchField = value;
                    this.RaisePropertyChanged("branch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Accounts", Namespace="http://schemas.datacontract.org/2004/07/KreationService")]
    [System.SerializableAttribute()]
    public partial class Accounts : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DebitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchId {
            get {
                return this.BranchIdField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchIdField, value) != true)) {
                    this.BranchIdField = value;
                    this.RaisePropertyChanged("BranchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Credit {
            get {
                return this.CreditField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditField, value) != true)) {
                    this.CreditField = value;
                    this.RaisePropertyChanged("Credit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Debit {
            get {
                return this.DebitField;
            }
            set {
                if ((object.ReferenceEquals(this.DebitField, value) != true)) {
                    this.DebitField = value;
                    this.RaisePropertyChanged("Debit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrNo {
            get {
                return this.TrNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TrNoField, value) != true)) {
                    this.TrNoField = value;
                    this.RaisePropertyChanged("TrNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/KreationService")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string barcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string invoicenoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string profitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string qtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string totalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string barcode {
            get {
                return this.barcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.barcodeField, value) != true)) {
                    this.barcodeField = value;
                    this.RaisePropertyChanged("barcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string invoiceno {
            get {
                return this.invoicenoField;
            }
            set {
                if ((object.ReferenceEquals(this.invoicenoField, value) != true)) {
                    this.invoicenoField = value;
                    this.RaisePropertyChanged("invoiceno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string price {
            get {
                return this.priceField;
            }
            set {
                if ((object.ReferenceEquals(this.priceField, value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string profit {
            get {
                return this.profitField;
            }
            set {
                if ((object.ReferenceEquals(this.profitField, value) != true)) {
                    this.profitField = value;
                    this.RaisePropertyChanged("profit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string qty {
            get {
                return this.qtyField;
            }
            set {
                if ((object.ReferenceEquals(this.qtyField, value) != true)) {
                    this.qtyField = value;
                    this.RaisePropertyChanged("qty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string total {
            get {
                return this.totalField;
            }
            set {
                if ((object.ReferenceEquals(this.totalField, value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KreationService.IKreationService")]
    public interface IKreationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/login", ReplyAction="http://tempuri.org/IKreationService/loginResponse")]
        string login([System.ServiceModel.MessageParameterAttribute(Name="login")] SAI.KreationService.Log login1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/login", ReplyAction="http://tempuri.org/IKreationService/loginResponse")]
        System.Threading.Tasks.Task<string> loginAsync(SAI.KreationService.Log login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/add_Ac", ReplyAction="http://tempuri.org/IKreationService/add_AcResponse")]
        int add_Ac(SAI.KreationService.Log login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/add_Ac", ReplyAction="http://tempuri.org/IKreationService/add_AcResponse")]
        System.Threading.Tasks.Task<int> add_AcAsync(SAI.KreationService.Log login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/Deleteusername", ReplyAction="http://tempuri.org/IKreationService/DeleteusernameResponse")]
        void Deleteusername(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/Deleteusername", ReplyAction="http://tempuri.org/IKreationService/DeleteusernameResponse")]
        System.Threading.Tasks.Task DeleteusernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/Searchusername", ReplyAction="http://tempuri.org/IKreationService/SearchusernameResponse")]
        void Searchusername(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/Searchusername", ReplyAction="http://tempuri.org/IKreationService/SearchusernameResponse")]
        System.Threading.Tasks.Task SearchusernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/up_Acc", ReplyAction="http://tempuri.org/IKreationService/up_AccResponse")]
        int up_Acc(SAI.KreationService.Accounts Accounts);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/up_Acc", ReplyAction="http://tempuri.org/IKreationService/up_AccResponse")]
        System.Threading.Tasks.Task<int> up_AccAsync(SAI.KreationService.Accounts Accounts);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/ed_acc", ReplyAction="http://tempuri.org/IKreationService/ed_accResponse")]
        int ed_acc(SAI.KreationService.Accounts Accounts);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/ed_acc", ReplyAction="http://tempuri.org/IKreationService/ed_accResponse")]
        System.Threading.Tasks.Task<int> ed_accAsync(SAI.KreationService.Accounts Accounts);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/accDetail", ReplyAction="http://tempuri.org/IKreationService/accDetailResponse")]
        System.Data.DataSet accDetail(SAI.KreationService.Accounts Account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/accDetail", ReplyAction="http://tempuri.org/IKreationService/accDetailResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> accDetailAsync(SAI.KreationService.Accounts Account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/add_prod", ReplyAction="http://tempuri.org/IKreationService/add_prodResponse")]
        int add_prod(SAI.KreationService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/add_prod", ReplyAction="http://tempuri.org/IKreationService/add_prodResponse")]
        System.Threading.Tasks.Task<int> add_prodAsync(SAI.KreationService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/ProDetail", ReplyAction="http://tempuri.org/IKreationService/ProDetailResponse")]
        System.Data.DataSet ProDetail(SAI.KreationService.Product Product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/ProDetail", ReplyAction="http://tempuri.org/IKreationService/ProDetailResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ProDetailAsync(SAI.KreationService.Product Product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/ed_prod", ReplyAction="http://tempuri.org/IKreationService/ed_prodResponse")]
        int ed_prod(SAI.KreationService.Product Product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/ed_prod", ReplyAction="http://tempuri.org/IKreationService/ed_prodResponse")]
        System.Threading.Tasks.Task<int> ed_prodAsync(SAI.KreationService.Product Product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/SearchGuest_BranchBorella", ReplyAction="http://tempuri.org/IKreationService/SearchGuest_BranchBorellaResponse")]
        System.Data.DataSet SearchGuest_BranchBorella();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/SearchGuest_BranchBorella", ReplyAction="http://tempuri.org/IKreationService/SearchGuest_BranchBorellaResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SearchGuest_BranchBorellaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/SearchGuest_BranchBamba", ReplyAction="http://tempuri.org/IKreationService/SearchGuest_BranchBambaResponse")]
        System.Data.DataSet SearchGuest_BranchBamba();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/SearchGuest_BranchBamba", ReplyAction="http://tempuri.org/IKreationService/SearchGuest_BranchBambaResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SearchGuest_BranchBambaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/SearchGuest_BranchWattala", ReplyAction="http://tempuri.org/IKreationService/SearchGuest_BranchWattalaResponse")]
        System.Data.DataSet SearchGuest_BranchWattala();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/SearchGuest_BranchWattala", ReplyAction="http://tempuri.org/IKreationService/SearchGuest_BranchWattalaResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SearchGuest_BranchWattalaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/SearchUser", ReplyAction="http://tempuri.org/IKreationService/SearchUserResponse")]
        System.Data.DataSet SearchUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/SearchUser", ReplyAction="http://tempuri.org/IKreationService/SearchUserResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SearchUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/GetPrice", ReplyAction="http://tempuri.org/IKreationService/GetPriceResponse")]
        int GetPrice(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/GetPrice", ReplyAction="http://tempuri.org/IKreationService/GetPriceResponse")]
        System.Threading.Tasks.Task<int> GetPriceAsync(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/Name", ReplyAction="http://tempuri.org/IKreationService/NameResponse")]
        string Name(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/Name", ReplyAction="http://tempuri.org/IKreationService/NameResponse")]
        System.Threading.Tasks.Task<string> NameAsync(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/InsertPos", ReplyAction="http://tempuri.org/IKreationService/InsertPosResponse")]
        void InsertPos(SAI.KreationService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/InsertPos", ReplyAction="http://tempuri.org/IKreationService/InsertPosResponse")]
        System.Threading.Tasks.Task InsertPosAsync(SAI.KreationService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/SearchAllProducts", ReplyAction="http://tempuri.org/IKreationService/SearchAllProductsResponse")]
        System.Data.DataSet SearchAllProducts(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/SearchAllProducts", ReplyAction="http://tempuri.org/IKreationService/SearchAllProductsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SearchAllProductsAsync(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/FillProducts", ReplyAction="http://tempuri.org/IKreationService/FillProductsResponse")]
        System.Data.DataSet FillProducts(string invoiceNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/FillProducts", ReplyAction="http://tempuri.org/IKreationService/FillProductsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FillProductsAsync(string invoiceNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/Get_Sum_of_Charges", ReplyAction="http://tempuri.org/IKreationService/Get_Sum_of_ChargesResponse")]
        string Get_Sum_of_Charges(string invoice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/Get_Sum_of_Charges", ReplyAction="http://tempuri.org/IKreationService/Get_Sum_of_ChargesResponse")]
        System.Threading.Tasks.Task<string> Get_Sum_of_ChargesAsync(string invoice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/delete_pos", ReplyAction="http://tempuri.org/IKreationService/delete_posResponse")]
        void delete_pos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/delete_pos", ReplyAction="http://tempuri.org/IKreationService/delete_posResponse")]
        System.Threading.Tasks.Task delete_posAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/productlist", ReplyAction="http://tempuri.org/IKreationService/productlistResponse")]
        SAI.KreationService.Product[] productlist(string invoiceno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/productlist", ReplyAction="http://tempuri.org/IKreationService/productlistResponse")]
        System.Threading.Tasks.Task<SAI.KreationService.Product[]> productlistAsync(string invoiceno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/delete_item", ReplyAction="http://tempuri.org/IKreationService/delete_itemResponse")]
        void delete_item(SAI.KreationService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKreationService/delete_item", ReplyAction="http://tempuri.org/IKreationService/delete_itemResponse")]
        System.Threading.Tasks.Task delete_itemAsync(SAI.KreationService.Product product);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKreationServiceChannel : SAI.KreationService.IKreationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KreationServiceClient : System.ServiceModel.ClientBase<SAI.KreationService.IKreationService>, SAI.KreationService.IKreationService {
        
        public KreationServiceClient() {
        }
        
        public KreationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KreationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KreationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KreationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string login(SAI.KreationService.Log login1) {
            return base.Channel.login(login1);
        }
        
        public System.Threading.Tasks.Task<string> loginAsync(SAI.KreationService.Log login) {
            return base.Channel.loginAsync(login);
        }
        
        public int add_Ac(SAI.KreationService.Log login) {
            return base.Channel.add_Ac(login);
        }
        
        public System.Threading.Tasks.Task<int> add_AcAsync(SAI.KreationService.Log login) {
            return base.Channel.add_AcAsync(login);
        }
        
        public void Deleteusername(string username) {
            base.Channel.Deleteusername(username);
        }
        
        public System.Threading.Tasks.Task DeleteusernameAsync(string username) {
            return base.Channel.DeleteusernameAsync(username);
        }
        
        public void Searchusername(string username) {
            base.Channel.Searchusername(username);
        }
        
        public System.Threading.Tasks.Task SearchusernameAsync(string username) {
            return base.Channel.SearchusernameAsync(username);
        }
        
        public int up_Acc(SAI.KreationService.Accounts Accounts) {
            return base.Channel.up_Acc(Accounts);
        }
        
        public System.Threading.Tasks.Task<int> up_AccAsync(SAI.KreationService.Accounts Accounts) {
            return base.Channel.up_AccAsync(Accounts);
        }
        
        public int ed_acc(SAI.KreationService.Accounts Accounts) {
            return base.Channel.ed_acc(Accounts);
        }
        
        public System.Threading.Tasks.Task<int> ed_accAsync(SAI.KreationService.Accounts Accounts) {
            return base.Channel.ed_accAsync(Accounts);
        }
        
        public System.Data.DataSet accDetail(SAI.KreationService.Accounts Account) {
            return base.Channel.accDetail(Account);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> accDetailAsync(SAI.KreationService.Accounts Account) {
            return base.Channel.accDetailAsync(Account);
        }
        
        public int add_prod(SAI.KreationService.Product product) {
            return base.Channel.add_prod(product);
        }
        
        public System.Threading.Tasks.Task<int> add_prodAsync(SAI.KreationService.Product product) {
            return base.Channel.add_prodAsync(product);
        }
        
        public System.Data.DataSet ProDetail(SAI.KreationService.Product Product) {
            return base.Channel.ProDetail(Product);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ProDetailAsync(SAI.KreationService.Product Product) {
            return base.Channel.ProDetailAsync(Product);
        }
        
        public int ed_prod(SAI.KreationService.Product Product) {
            return base.Channel.ed_prod(Product);
        }
        
        public System.Threading.Tasks.Task<int> ed_prodAsync(SAI.KreationService.Product Product) {
            return base.Channel.ed_prodAsync(Product);
        }
        
        public System.Data.DataSet SearchGuest_BranchBorella() {
            return base.Channel.SearchGuest_BranchBorella();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SearchGuest_BranchBorellaAsync() {
            return base.Channel.SearchGuest_BranchBorellaAsync();
        }
        
        public System.Data.DataSet SearchGuest_BranchBamba() {
            return base.Channel.SearchGuest_BranchBamba();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SearchGuest_BranchBambaAsync() {
            return base.Channel.SearchGuest_BranchBambaAsync();
        }
        
        public System.Data.DataSet SearchGuest_BranchWattala() {
            return base.Channel.SearchGuest_BranchWattala();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SearchGuest_BranchWattalaAsync() {
            return base.Channel.SearchGuest_BranchWattalaAsync();
        }
        
        public System.Data.DataSet SearchUser() {
            return base.Channel.SearchUser();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SearchUserAsync() {
            return base.Channel.SearchUserAsync();
        }
        
        public int GetPrice(string ID) {
            return base.Channel.GetPrice(ID);
        }
        
        public System.Threading.Tasks.Task<int> GetPriceAsync(string ID) {
            return base.Channel.GetPriceAsync(ID);
        }
        
        public string Name(string ID) {
            return base.Channel.Name(ID);
        }
        
        public System.Threading.Tasks.Task<string> NameAsync(string ID) {
            return base.Channel.NameAsync(ID);
        }
        
        public void InsertPos(SAI.KreationService.Product product) {
            base.Channel.InsertPos(product);
        }
        
        public System.Threading.Tasks.Task InsertPosAsync(SAI.KreationService.Product product) {
            return base.Channel.InsertPosAsync(product);
        }
        
        public System.Data.DataSet SearchAllProducts(string ID) {
            return base.Channel.SearchAllProducts(ID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SearchAllProductsAsync(string ID) {
            return base.Channel.SearchAllProductsAsync(ID);
        }
        
        public System.Data.DataSet FillProducts(string invoiceNo) {
            return base.Channel.FillProducts(invoiceNo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FillProductsAsync(string invoiceNo) {
            return base.Channel.FillProductsAsync(invoiceNo);
        }
        
        public string Get_Sum_of_Charges(string invoice) {
            return base.Channel.Get_Sum_of_Charges(invoice);
        }
        
        public System.Threading.Tasks.Task<string> Get_Sum_of_ChargesAsync(string invoice) {
            return base.Channel.Get_Sum_of_ChargesAsync(invoice);
        }
        
        public void delete_pos() {
            base.Channel.delete_pos();
        }
        
        public System.Threading.Tasks.Task delete_posAsync() {
            return base.Channel.delete_posAsync();
        }
        
        public SAI.KreationService.Product[] productlist(string invoiceno) {
            return base.Channel.productlist(invoiceno);
        }
        
        public System.Threading.Tasks.Task<SAI.KreationService.Product[]> productlistAsync(string invoiceno) {
            return base.Channel.productlistAsync(invoiceno);
        }
        
        public void delete_item(SAI.KreationService.Product product) {
            base.Channel.delete_item(product);
        }
        
        public System.Threading.Tasks.Task delete_itemAsync(SAI.KreationService.Product product) {
            return base.Channel.delete_itemAsync(product);
        }
    }
}
